"use client";

import { createContext, useContext, useEffect, useState } from "react";

export type LangCode = "es" | "en" | "fr";

export interface Language {
  code: LangCode;
  label: string;
  flag: string;
}

export const LANGUAGES: Language[] = [
  { code: "es", label: "Español",  flag: "🇪🇸" },
  { code: "en", label: "English",  flag: "🇬🇧" },
  { code: "fr", label: "Français", flag: "🇫🇷" },
];

export const translations = {
  es: {
    // Header / menú usuario
    darkMode:            "Modo oscuro",
    changeLanguage:      "Cambiar idioma",
    logout:              "Cerrar sesión",
    headerSubtitle:      "Plataforma de gestión de reservas y cobros",
    errorLoadingBusinesses: "Hubo un error al cargar los negocios. Por favor, inténtalo de nuevo.",
  
    // Sidebar
    dashboard:           "Dashboard",
    bookings:            "Reservas",
    customers:           "Clientes",
    payments:            "Pagos",
    business:            "Negocio",
    adminWorkspace:      "Panel de administración",

    // Dashboard
    dashboardTitle:      "Panel de control",
    dashboardSubtitle:   "Control diario de reservas, actividad y pagos.",
    totalBookings:       "Total reservas",
    totalBookingsSub:    "Registros en base de datos",
    pending:             "Pendientes",
    pendingSub:          "Por confirmar",
    confirmed:           "Confirmadas",
    confirmedSub:        "En agenda",
    paid:                "Pagadas",
    paidSub:             "Completadas",
    upcomingBookings:    "Próximas reservas",
    viewAll:             "Ver todas",
    noBookingsYet:       "No hay reservas registradas todavía.",
    date:                "Fecha",
    time:                "Hora",
    service:             "Servicio",
    status:              "Estado",
    registeredInSystem:  "Registradas en el sistema",
    pendingToConfirm:    "Pendientes de confirmar",
    requireFollowUp:     "Requieren seguimiento",
    closedBookings:      "Reservas cerradas",
    statusPending:       "Pendiente",
    statusConfirmed:     "Confirmada",
    statusPaid:          "Pagada",
    statusCancelled:     "Cancelada",

    // Bookings
    bookingsTitle:       "Panel de Citas",
    bookingsSubtitle:    "Visualización y gestión de citas programadas y próximas reservas.",
    newBooking:          "+ Nueva Reserva",
    total:               "Total",
    historical:          "Histórico",
    inAgenda:            "En agenda",
    completed:           "Completado",
    upcomingAppointments:"Próximas Citas",
    clientId:            "ID Cliente",
    serviceCol:          "SERVICIO",
    dateTime:            "FECHA Y HORA",
    statusCol:           "ESTADO",
    actionsCol:          "ACCIONES",
    edit:                "Editar",
    delete:              "Borrar",
    confirmDelete:       "¿Eliminar esta reserva?",
    updateAppointment:   "Actualizar Cita",
    newAppointment:      "Nueva Reserva",
    fillFields:          "Completa los campos para organizar la agenda.",
    serviceLabel:        "Servicio",
    dateLabel:           "Fecha",
    timeLabel:           "Hora",
    businessLabel:       "Negocio",
    selectBusiness:      "Selecciona un negocio",
    clientLabel:         "Cliente",
    selectClient:        "Selecciona un cliente",
    statusLabel:         "Estado",
    cancel:              "Cancelar",
    finish:              "Finalizar",
    savedOk:             "Cambios guardados con éxito",
    createdOk:           "Cita programada correctamente",
    errorMsg:            "No pudimos procesar la solicitud",
    filterAll:           "Ver todas",

    // Customers
    customersTitle:      "Listado de clientes",
    customersSubtitle:   "Gestión visual de clientes y próximas reservas.",
    newCustomer:         "Nuevo cliente",
    searchCustomer:      "Buscar cliente...",
    clearSearch:         "Limpiar",
    nextBooking:         "Próxima reserva:",
    noNextBooking:       "Sin reservas próximas",
    newCustomerModal:    "Nuevo cliente",
    namePlaceholder:     "Nombre",
    phonePlaceholder:    "Teléfono",
    emailPlaceholder:    "Email",
    businessPlaceholder: "Negocio",
    save:                "Guardar",
    customerCreated:     "Cliente creado correctamente",
    errName:             "El nombre es obligatorio",
    errPhone:            "El teléfono es obligatorio",
    errPhoneFormat:      "El teléfono debe tener 9 dígitos",
    errEmail:            "El email es obligatorio",
    errEmailFormat:      "El email no es válido",
    errBusiness:         "El negocio es obligatorio",

    // Payments
    paymentsTitle:       "Payments",
    paymentsSubtitle:    "Seguimiento de cobros realizados y pendientes.",
    registerPayment:     "Registrar cobro",
    collected:           "Cobrado",
    operations:          "operaciones",
    toReview:            "por revisar",
    paymentList:         "Listado de cobros",
    noPaymentsCategory:  "No hay cobros en esta categoría",
    amount:              "Importe",
    method:              "Método",
    reservation:         "Reserva",
    markPaid:            "Marcar pagado",
    markPending:         "Marcar pendiente",
    registerPaymentModal:"Registrar cobro",
    amountPlaceholder:   "Importe (€)",
    paymentMethod:       "Método de pago",
    card:                "Tarjeta",
    cash:                "Efectivo",
    transfer:            "Transferencia",
    toPay:               "Por cobrar",
    selectReservation:   "Selecciona una reserva",
    paymentRegistered:   "Cobro registrado correctamente",
    markedPaid:          "Reserva marcada como pagada",
    markedPending:       "Reserva marcada como pendiente",
    pendingFilter:       "Pendientes",
    paidFilter:          "Pagados",
    seeAll:              "Ver todos",

    // Business
    businessTitle:       "Negocios",
    businessSubtitle:    "Gestión de negocios registrados en la plataforma.",
    newBusiness:         "Nuevo negocio",
    active:              "Activo",
    inactive:            "Inactivo",
    newBusinessModal:    "Nuevo negocio",
    nameBusiness:        "Nombre del negocio",
    category:            "Categoría",
    address:             "Dirección",
    businessCreated:     "Negocio creado correctamente",
    name:                "Nombre",
    email:               "Email",
    phone:               "Teléfono",
    statusBusiness:      "Estado",

    // Cliente sidebar / área cliente
    mySpace:                  "Mi espacio",
    myBusinesses:             "Empresas",
    myBookings:               "Mis Reservas",
    myProfile:                "Mi perfil",
    account:                  "Cuenta",
    settings:                 "Ajustes",
    clientRole:               "Cliente",
    bookingPortal:            "Portal de reservas",
    search:                    "Buscar",

    // Mis Reservas (página cliente)
    misReservasTitle:         "Mis Reservas",
    misReservasSubtitle:      "Historial de todas tus citas y su estado actual.",
    newReservation:           "+ Nueva Reserva",
    reservasCount:            "reservas",
    appointments:             "Citas",
    loadingText:              "Cargando...",
    noReservas:               "Aún no tienes reservas.",
    exploreBusinesses:        "Explorar negocios",

    // Nueva Reserva (página cliente)
    nuevaReservaTitle:        "Nueva Reserva",
    nuevaReservaSubtitle:     "Elige un negocio, el servicio y la fecha.",
    goBack:                   "← Volver",
    businessFieldLabel:       "Negocio *",
    selectBusinessOption:     "Selecciona un negocio",
    serviceFieldLabel:        "Servicio *",
    servicePlaceholder:       "Ej: Corte de pelo, Masaje, Consulta...",
    dateFieldLabel:           "Fecha *",
    timeFieldLabel:           "Hora *",
    fillAllFields:            "Completa todos los campos.",
    sendingText:              "Enviando...",
    confirmReservation:       "Confirmar reserva",
    reservaCreada:            "¡Reserva creada!",
    reservaCreadaMsg:         "Tu cita está pendiente de confirmación por el negocio.",
    verMisReservas:           "Ver mis reservas",
    volverEmpresas:           "Volver a empresas",
    errorCrearReserva:        "Error al crear la reserva. Inténtalo de nuevo.",
    preselectedBusiness:      "seleccionado",

    // Export
    exportReport:             "Exportar informe",
    noBookingsExport:         "No hay reservas para exportar.",

    // Bookings KPIs
    kpiCancelled:             "Canceladas",
    kpiCancelledSub:          "Anuladas",
    upcomingAppointmentsPanel:"Próximas Citas",

    // Filter pills
    filterPaid:               "Pagadas",
    filterCancelled:          "Canceladas",

    // Delete modal
    deleteModalTitle:         "Eliminar reserva",
    deleteModalText:          "¿Seguro que quieres eliminar la reserva",
    deleteModalUndo:          "Esta acción no se puede deshacer.",
    deletedOk:                "Reserva eliminada correctamente",

    // Quick create shared
    quickSaving:              "Guardando...",
    quickAddNew:              "+ Nuevo",

    // Quick create customer
    quickNewCustomer:         "Nuevo cliente",
    quickNewCustomerDesc:     "Rellena los datos del nuevo cliente. Se guardará automáticamente.",
    quickNameLabel:           "Nombre *",
    quickNamePlaceholder:     "Nombre completo",
    quickEmailLabel:          "Email *",
    quickEmailPlaceholder:    "correo@ejemplo.com",
    quickPhoneLabel:          "Teléfono *",
    quickPhonePlaceholder:    "612 345 678",
    quickBusinessOptLabel:    "Negocio (opcional)",
    quickBusinessPlaceholder: "Nombre del negocio",
    quickCreateCustomer:      "Crear cliente",
    quickCustomerCreated:     "Cliente creado correctamente",
    quickCustomerError:       "Error al crear el cliente. Inténtalo de nuevo.",
    quickCustomerValidation:  "Nombre, email y teléfono son obligatorios.",

    // Quick create business
    quickNewBusiness:         "Nuevo negocio",
    quickNewBusinessDesc:     "Rellena los datos del nuevo negocio. Se guardará automáticamente.",
    quickAddressLabel:        "Dirección *",
    quickAddressPlaceholder:  "Calle, número, ciudad",
    quickCategoryLabel:       "Categoría",
    quickCategoryPlaceholder: "Peluquería, Spa...",
    quickOwnerEmailLabel:     "Email del propietario *",
    quickOwnerEmailPlaceholder:"propietario@ejemplo.com",
    quickOwnerPassLabel:      "Contraseña del propietario *",
    quickOwnerPassPlaceholder:"Mínimo 6 caracteres",
    quickCreateBusiness:      "Crear negocio",
    quickBusinessCreated:     "Negocio creado correctamente",
    quickBusinessError:       "Error al crear el negocio. Inténtalo de nuevo.",
    quickBusinessValidation:  "Nombre, dirección, email y contraseña del propietario son obligatorios.",

    // Empresas (página cliente)
    empresasTitle:            "Empresas disponibles",
    empresasSubtitle:         "Encuentra un negocio y reserva tu cita al instante.",
    activeBusinesses:         "Negocios activos",
    searchBusinessPlaceholder:"Buscar por nombre, categoría...",
    loadingBusinesses:        "Cargando negocios...",
    noBusinessesFound:        "No se encontraron negocios.",
    bookNow:                  "Reservar",
    businessCol:              "Negocio",
    categoryCol:              "Categoría",
    phoneCol:                 "Teléfono",
    addressCol:               "Dirección",
    bookCol:                  "Reservar",

    // Configuración
    configTitle:              "Configuración",
    configSubtitle:           "Ajustes de la plataforma",
    configComingSoon:         "Próximamente — Opciones de configuración",

    // Business-Bookings (negocio)
    myBusinessBookings:       "Mis Reservas",
    bbHistorical:             "Histórico",
    bbPending:                "Pendientes",
    bbConfirmed:              "Confirmadas",
    bbPaid:                   "Pagadas",
    bbPendingSub:             "Por confirmar",
    bbConfirmedSub:           "En agenda",
    bbPaidSub:                "Completado",
    bbTotalSub:               "Total",
    appointmentList:          "Listado de citas",
    searchServiceClient:      "Buscar servicio o cliente...",
    loadingBookings:          "Cargando reservas...",
    noBookingsFilter:         "No hay reservas con estos filtros.",
    serviceCol2:              "SERVICIO",
    clientCol:                "CLIENTE",
    actionCol:                "ACCIÓN",
    confirmAction:            "Confirmar",
    markPaidAction:           "Marcar pagada",
    completed2:               "Completada",
    bbStatusAll:              "Todas",
    bbStatusPending:          "Pendiente",
    bbStatusConfirmed:        "Confirmada",
    bbStatusPaid:             "Pagada",
    bbNewBooking:             "+ Nueva Reserva",
    bbNewBookingTitle:        "Nueva Reserva",
    bbNewBookingDesc:         "Rellena los datos de la reserva.",
    bbServiceLabel:           "Servicio",
    bbServicePlaceholder:     "Ej: Corte de pelo",
    bbDateLabel:              "Fecha",
    bbTimeLabel:              "Hora",
    bbClientLabel:            "Cliente",
    bbNewClientBtn:           "+ Nuevo cliente",
    bbCancelNewClient:        "✕ Cancelar nuevo",
    bbClientNamePlaceholder:  "Nombre *",
    bbClientPhonePlaceholder: "Teléfono (opcional)",
    bbSaveSelectClient:       "Guardar y seleccionar",
    bbSaving:                 "Guardando...",
    bbSelectClient:           "Selecciona un cliente",
    bbInitialStatus:          "Estado inicial",
    bbStatusPendingOpt:       "Pendiente",
    bbStatusConfirmedOpt:     "Confirmada",
    bbCancelBtn:              "Cancelar",
    bbCreateBtn:              "Crear reserva",
    bbStatusUpdated:          "Estado actualizado correctamente",
    bbStatusError:            "No se pudo actualizar el estado",
    bbClientCreated:          "cliente creado y seleccionado",
    bbClientError:            "No se pudo crear el cliente",
    bbBookingCreated:         "Reserva creada correctamente",
    bbBookingError:           "No se pudo crear la reserva",

    // Settings (ajustes cliente)
    settingsTitle:            "Ajustes",
    settingsSubtitle:         "Gestiona tu cuenta y preferencias.",
    settingsLanguage:         "Idioma",
    settingsAppearance:       "Apariencia",
    settingsDarkMode:         "Modo oscuro",
    settingsPassword:         "Cambiar contraseña",
    settingsCurrentPw:        "Contraseña actual",
    settingsNewPw:            "Nueva contraseña",
    settingsNewPwMin:         "Mínimo 6 carac. (letra y número)",
    settingsConfirmPw:        "Confirmar nueva contraseña",
    settingsRepeatPw:         "Repite la contraseña",
    settingsSaving:           "Guardando...",
    settingsUpdatePw:         "Actualizar contraseña",
    settingsPwUpdated:        "Contraseña actualizada correctamente.",
    settingsPwError:          "Error al cambiar la contraseña.",
    settingsPwMismatch:       "Las contraseñas no coinciden.",
    settingsPwMinLen:         "Mínimo 6 caracteres, con al menos una letra y un número.",
    pwFormatHint:             "Mínimo 6 caracteres, conteniendo al menos una letra y un número.",
    settings2FA:              "Autenticación en dos pasos",
    settings2FADesc:          "Añade una capa extra de seguridad a tu cuenta. Recibirás un código cada vez que inicies sesión.",
    settings2FAActive:        "Activada",
    settings2FAInactive:      "Desactivada",
    settings2FAStatus:        "Estado:",
    settings2FAEnable:        "Activar 2FA",
    settings2FADisable:       "Desactivar",
    settingsSession:          "Sesión",
    settingsSessionDesc:      "Cierra tu sesión en este dispositivo.",
    settingsLogout:           "Cerrar sesión",
    modal2FATitle:            "autenticación en dos pasos",
    modal2FAEnableTitle:      "Activar",
    modal2FADisableTitle:     "Desactivar",
    modal2FAEnableMsg:        "Al activar 2FA, recibirás un código por email cada vez que inicies sesión. ¿Continuar?",
    modal2FADisableMsg:       "¿Seguro que quieres desactivar la autenticación en dos pasos? Tu cuenta será menos segura.",
    modal2FAConfirmEnable:    "Sí, activar",
    modal2FAConfirmDisable:   "Sí, desactivar",

    // Admin Sidebar labels
    myBusiness:               "Mi negocio",
    sidebarManagement:        "Gestión",
    sidebarSystem:            "Sistema",
    sidebarConfig:            "Configuración",
    sidebarBusinessRole:      "Negocio verificado",
    sidebarAdminRole:         "Administrador",
    sidebarServices:          "Mis Servicios",

    // ConfigTabs
    configAdminGlobal:        "Ajustes Globales (Admin)",
    configSystemTimezone:     "Zona Horaria del Sistema",
    configMainCurrency:       "Moneda Principal",
    configActiveUsers:        "Gestión de Usuarios Activos",
    configNewUserVerification:"Nuevos registros requieren verificación",
    configBusinessSettingsTitle:"Configuración del Negocio",
    configHoursAndBookings:   "Horarios y Citas",
    configDefaultDuration:    "Duración por defecto de cada cita (minutos)",
    configMarginBetween:      "Margen entre citas (minutos)",
    configBookingPolicies:    "Políticas de Reserva",
    configMinAdvance:         "Antelación mínima para reservar (horas)",
    configMaxBookings:        "Límite de reservas por cliente (al día)",
    configCustomerPrefs:      "Preferencias de Cliente",
    configNotificationsTitle: "Notificaciones",
    configEmailReminders:     "Recordatorios por Email (24h antes)",
    configSMSReminders:       "Recordatorios por SMS",
    configPromotions:         "Promociones y novedades",
    configPrivacyTitle:       "Privacidad",
    configRequestDeletion:    "Solicitar eliminación de cuenta",
    configTabAdmin:           "Administración",
    configTabBusiness:        "Mi Negocio",
    configTabCustomer:        "Mi Cuenta",
    saveChanges:              "Guardar cambios",
    configSavedText:          "¡Guardado!",

    // Admin User Management
    adminManageUsers:         "Gestión de Usuarios",
    adminEmail:               "Email",
    adminNewPassword:         "Nueva contraseña (dejar en blanco para no cambiar)",
    adminEditUser:            "Editar",
    adminDeleteUser:          "Eliminar",
    adminSaveUser:            "Guardar",
    adminCancel:              "Cancelar",
    adminConfirmDelete:       "¿Estás seguro de que quieres eliminar este usuario? Esta acción es irreversible.",
    adminNoUsers:             "No se encontraron otros usuarios.",
    adminLoadingUsers:        "Cargando usuarios...",

    // Login / Registro
    loginTitle:               "Iniciar sesión",
    loginSubtitle:            "Accede a tu panel de control",
    emailLabel:               "Correo electrónico",
    passwordLabel:            "Contraseña",
    loginBtn:                 "Entrar →",
    loggingIn:                "Entrando...",
    createCustomerBtn:        "Crear cuenta de cliente",
    registerBusinessPremium:  "Registrar mi empresa (Premium)",
    customerRegisterTitle:    "Crear cuenta",
    customerRegisterSub:      "Regístrate como cliente particular",
    fullNameLabel:            "Nombre completo",
    mobilePhoneLabel:         "Teléfono móvil",
    confirmPasswordLabel:     "Confirmar contraseña",
    registerCustomerBtn:      "Registrarse e iniciar sesión →",
    registeringText:          "Registrando...",
    alreadyHaveAccount:       "¿Ya tienes cuenta? Inicia sesión",
    businessRegisterTitle:    "Registrar empresa",
    bizNameLabel:             "Nombre de la empresa *",
    bizAddressLabel:          "Dirección de la empresa *",
    bizCategoryLabel:         "Categoría",
    bizPhoneLabel:            "Teléfono móvil",
    ownerEmailLabel:          "Correo del propietario *",
    ownerPasswordLabel:       "Contraseña *",
    confirmOwnerPasswordLabel: "Confirmar *",
    continueToPayment:        "Continuar al pago →",
    monthlySubPro:            "Suscripción Mensual Pro",
    subPriceMonth:            "14,99 € / mes",
    subFeatures:              "✓ Panel de administración de reservas completo\n✓ Enlace personalizado para tus clientes\n✓ Configuración de horarios y servicios ilimitados\n✓ Soporte 24/7 y facturación mensual",
    cardHolderLabel:          "Titular de la tarjeta",
    cardNumberLabel:          "Número de tarjeta",
    cardExpiryLabel:          "Vencimiento",
    payAndCreateAccount:      "Pagar 14,99 € y crear cuenta →",
    modifyingDataBtn:         "← Modificar datos",
    secureAccessSSL:          "Acceso protegido y cifrado SSL",
    cardNameRequired:         "Por favor, rellena todos los datos de tu tarjeta de crédito.",
    processingSecurePayment:  "Procesando pago seguro...",
    fillAllRequired:          "Por favor, rellena todos los campos obligatorios.",
    loginHeroTitle:           "Gestiona reservas\nde forma inteligente",
    loginHeroDesc:            "Plataforma moderna para administrar citas, reservas y clientes desde un panel elegante y rápido.",
    loginStatBookings:        "Reservas",
    loginStatBusinesses:      "Negocios",
    loginFormSubDefault:      "Accede a tu panel administrativo",
    loginFormSubBizPayment:   "Introduce tus datos bancarios para activar la suscripción",
    loginFormSubBizData:      "Introduce los datos de tu nuevo negocio",
    fullNamePlaceholder:      "Juan Pérez",
    bizNamePlaceholder:       "Mi Negocio S.L.",
    bizAddressPlaceholder:    "Calle Mayor 12, Alicante",
    bizCategoryPlaceholder:   "Peluquería",
    ownerEmailPlaceholder:    "propietario@empresa.com",
    ownerPasswordPlaceholder: "Mínimo 6 carac.",
    repeatPasswordPlaceholder: "Repite tu contraseña",
    cardHolderPlaceholder:    "Nombre Completo",
    subPriceMonthText:        "14,99 € / mes",
    payAndCreateAccountText:  "Pagar 14,99 € y crear cuenta →",
    loginErrorIncorrect:      "Correo o contraseña incorrectos.",
    invalidEmail:             "Por favor, introduce un correo electrónico válido.",
    phoneMinLength:           "El teléfono móvil debe tener al menos 9 dígitos.",
    passwordsMismatch:        "Las contraseñas no coinciden.",
    passwordMinLength:        "La contraseña debe tener al menos 6 caracteres.",
    passwordFormat:           "La contraseña debe contener al menos una letra y un número.",
    registrationError:        "Hubo un error al crear la cuenta. Inténtalo de nuevo.",
    showPasswordLabel:        "Mostrar",
    hidePasswordLabel:        "Ocultar",
    accountSecurity:          "Seguridad de la cuenta",
    introduceCurrentPw:       "Introduce tu contraseña actual",
    profileSecTitle:          "Tu cuenta es segura",
    profileSecDesc:           "Tu contraseña actual está protegida mediante encriptación hash en la base de datos. Se recomienda actualizarla de manera periódica.",
    userPanelTitle:           "Panel de Usuario",
    userPanelSubtitle:        "Gestiona tus citas y reserva en tus locales favoritos",
    password:                 "Contraseña",
    conversionRate:           "Tasa de conversión",
    paidVsTotal:              "Pagadas vs Total",
    actionRequired:           "Acción requerida",
    requireAttention:         "Requieren atención",
    totalRevenue:             "Ingresos Totales",
    revenueSubtitle:          "Facturación acumulada",
    pendingCollection:        "Pendiente de cobro",
    pendingPayments:          "Pendientes de pago",
  },

  en: {
    headerSubtitle:      "Booking and payment management platform",
    darkMode:            "Dark mode",
    changeLanguage:      "Change language",
    logout:              "Log out",
    dashboard:           "Dashboard",
    bookings:            "Bookings",
    customers:           "Customers",
    payments:            "Payments",
    business:            "Business",
    adminWorkspace:      "Admin workspace",
    dashboardTitle:      "Dashboard overview",
    dashboardSubtitle:   "Daily overview of bookings, activity and payments.",
    totalBookings:       "Total bookings",
    totalBookingsSub:    "Records in database",
    pending:             "Pending",
    pendingSub:          "To confirm",
    confirmed:           "Confirmed",
    confirmedSub:        "In schedule",
    paid:                "Paid",
    paidSub:             "Completed",
    upcomingBookings:    "Upcoming bookings",
    viewAll:             "View all",
    noBookingsYet:       "No bookings registered yet.",
    date:                "Date",
    time:                "Time",
    service:             "Service",
    status:              "Status",
    registeredInSystem:  "Registered in the system",
    pendingToConfirm:    "Pending to confirm",
    requireFollowUp:     "Require follow-up",
    closedBookings:      "Closed bookings",
    statusPending:       "Pending",
    statusConfirmed:     "Confirmed",
    statusPaid:          "Paid",
    statusCancelled:     "Cancelled",
    bookingsTitle:       "Appointments Panel",
    bookingsSubtitle:    "Visualisation and management of scheduled appointments and upcoming bookings.",
    newBooking:          "+ New Booking",
    total:               "Total",
    historical:          "Historical",
    inAgenda:            "In schedule",
    completed:           "Completed",
    upcomingAppointments:"Upcoming Appointments",
    clientId:            "Client ID",
    serviceCol:          "SERVICE",
    dateTime:            "DATE & TIME",
    statusCol:           "STATUS",
    actionsCol:          "ACTIONS",
    edit:                "Edit",
    delete:              "Delete",
    confirmDelete:       "Delete this booking?",
    updateAppointment:   "Update Appointment",
    newAppointment:      "New Booking",
    fillFields:          "Fill in the fields to organise the schedule.",
    serviceLabel:        "Service",
    dateLabel:           "Date",
    timeLabel:           "Time",
    businessLabel:       "Business",
    selectBusiness:      "Select a business",
    clientLabel:         "Client",
    selectClient:        "Select a client",
    statusLabel:         "Status",
    cancel:              "Cancel",
    finish:              "Confirm",
    savedOk:             "Changes saved successfully",
    createdOk:           "Appointment scheduled successfully",
    errorMsg:            "We could not process the request",
    filterAll:           "All",
    customersTitle:      "Customer directory",
    customersSubtitle:   "Visual management of customers and upcoming bookings.",
    newCustomer:         "New customer",
    searchCustomer:      "Search customer...",
    clearSearch:         "Clear",
    nextBooking:         "Next booking:",
    noNextBooking:       "No upcoming bookings",
    newCustomerModal:    "New customer",
    namePlaceholder:     "Name",
    phonePlaceholder:    "Phone",
    emailPlaceholder:    "Email",
    businessPlaceholder: "Business",
    save:                "Save",
    customerCreated:     "Customer created successfully",
    errName:             "Name is required",
    errPhone:            "Phone is required",
    errPhoneFormat:      "Phone must have 9 digits",
    errEmail:            "Email is required",
    errEmailFormat:      "Email is not valid",
    errBusiness:         "Business is required",
    paymentsTitle:       "Payments",
    paymentsSubtitle:    "Track completed and pending payments.",
    registerPayment:     "Register payment",
    collected:           "Collected",
    operations:          "operations",
    toReview:            "to review",
    paymentList:         "Payment list",
    noPaymentsCategory:  "No payments in this category",
    amount:              "Amount",
    method:              "Method",
    reservation:         "Booking",
    markPaid:            "Mark as paid",
    markPending:         "Mark as pending",
    registerPaymentModal:"Register payment",
    amountPlaceholder:   "Amount (€)",
    paymentMethod:       "Payment method",
    card:                "Card",
    cash:                "Cash",
    transfer:            "Transfer",
    toPay:               "To collect",
    selectReservation:   "Select a booking",
    paymentRegistered:   "Payment registered successfully",
    markedPaid:          "Booking marked as paid",
    markedPending:       "Booking marked as pending",
    pendingFilter:       "Pending",
    paidFilter:          "Paid",
    seeAll:              "See all",
    businessTitle:       "Businesses",
    businessSubtitle:    "Management of businesses registered on the platform.",
    newBusiness:         "New business",
    active:              "Active",
    inactive:            "Inactive",
    newBusinessModal:    "New business",
    nameBusiness:        "Business name",
    category:            "Category",
    address:             "Address",
    businessCreated:     "Business created successfully",
    name:                "Name",
    email:               "Email",
    phone:               "Phone",
    statusBusiness:      "Status",
    password:            "Password",

    // Cliente sidebar / área cliente
    mySpace:                  "My space",
    myBusinesses:             "Businesses",
    myBookings:               "My Bookings",
    account:                  "Account",
    settings:                 "Settings",
    clientRole:               "Client",
    bookingPortal:            "Booking portal",
    search:                   "Search",
    myProfile:                "My profile",

    // Mis Reservas (página cliente)
    misReservasTitle:         "My Bookings",
    misReservasSubtitle:      "History of all your appointments and their current status.",
    newReservation:           "+ New Booking",
    reservasCount:            "bookings",
    appointments:             "Appointments",
    loadingText:              "Loading...",
    noReservas:               "You have no bookings yet.",
    exploreBusinesses:        "Explore businesses",

    // Nueva Reserva (página cliente)
    nuevaReservaTitle:        "New Booking",
    nuevaReservaSubtitle:     "Choose a business, the service and the date.",
    goBack:                   "← Back",
    businessFieldLabel:       "Business *",
    selectBusinessOption:     "Select a business",
    serviceFieldLabel:        "Service *",
    servicePlaceholder:       "E.g. Haircut, Massage, Consultation...",
    dateFieldLabel:           "Date *",
    timeFieldLabel:           "Time *",
    fillAllFields:            "Please fill in all fields.",
    sendingText:              "Sending...",
    confirmReservation:       "Confirm booking",
    reservaCreada:            "Booking created!",
    reservaCreadaMsg:         "Your appointment is pending confirmation by the business.",
    verMisReservas:           "View my bookings",
    volverEmpresas:           "Back to businesses",
    errorCrearReserva:        "Error creating the booking. Please try again.",
    preselectedBusiness:      "selected",

    // Export
    exportReport:             "Export report",
    noBookingsExport:         "No bookings to export.",

    // Bookings KPIs
    kpiCancelled:             "Cancelled",
    kpiCancelledSub:          "Cancelled",
    upcomingAppointmentsPanel:"Upcoming Appointments",

    // Filter pills
    filterPaid:               "Paid",
    filterCancelled:          "Cancelled",

    // Delete modal
    deleteModalTitle:         "Delete booking",
    deleteModalText:          "Are you sure you want to delete booking",
    deleteModalUndo:          "This action cannot be undone.",
    deletedOk:                "Booking deleted successfully",

    // Quick create shared
    quickSaving:              "Saving...",
    quickAddNew:              "+ New",

    // Quick create customer
    quickNewCustomer:         "New customer",
    quickNewCustomerDesc:     "Fill in the new customer's details. It will be saved automatically.",
    quickNameLabel:           "Name *",
    quickNamePlaceholder:     "Full name",
    quickEmailLabel:          "Email *",
    quickEmailPlaceholder:    "mail@example.com",
    quickPhoneLabel:          "Phone *",
    quickPhonePlaceholder:    "612 345 678",
    quickBusinessOptLabel:    "Business (optional)",
    quickBusinessPlaceholder: "Business name",
    quickCreateCustomer:      "Create customer",
    quickCustomerCreated:     "Customer created successfully",
    quickCustomerError:       "Error creating the customer. Please try again.",
    quickCustomerValidation:  "Name, email and phone are required.",

    // Quick create business
    quickNewBusiness:         "New business",
    quickNewBusinessDesc:     "Fill in the new business details. It will be saved automatically.",
    quickAddressLabel:        "Address *",
    quickAddressPlaceholder:  "Street, number, city",
    quickCategoryLabel:       "Category",
    quickCategoryPlaceholder: "Hair salon, Spa...",
    quickOwnerEmailLabel:     "Owner email *",
    quickOwnerEmailPlaceholder:"owner@example.com",
    quickOwnerPassLabel:      "Owner password *",
    quickOwnerPassPlaceholder:"At least 6 characters",
    quickCreateBusiness:      "Create business",
    quickBusinessCreated:     "Business created successfully",
    quickBusinessError:       "Error creating the business. Please try again.",
    quickBusinessValidation:  "Name, address, email and owner password are required.",

    // Empresas (client page)
    empresasTitle:            "Available businesses",
    empresasSubtitle:         "Find a business and book your appointment instantly.",
    activeBusinesses:         "Active businesses",
    searchBusinessPlaceholder:"Search by name, category...",
    loadingBusinesses:        "Loading businesses...",
    noBusinessesFound:        "No businesses found.",
    bookNow:                  "Book",
    businessCol:              "Business",
    categoryCol:              "Category",
    phoneCol:                 "Phone",
    addressCol:               "Address",
    bookCol:                  "Book",

    // Configuración
    configTitle:              "Settings",
    configSubtitle:           "Platform settings",
    configComingSoon:         "Coming soon — Configuration options",

    // Business-Bookings
    myBusinessBookings:       "My Bookings",
    bbHistorical:             "Historical",
    bbPending:                "Pending",
    bbConfirmed:              "Confirmed",
    bbPaid:                   "Paid",
    bbPendingSub:             "To confirm",
    bbConfirmedSub:           "In schedule",
    bbPaidSub:                "Completed",
    bbTotalSub:               "Total",
    appointmentList:          "Appointment list",
    searchServiceClient:      "Search service or client...",
    loadingBookings:          "Loading bookings...",
    noBookingsFilter:         "No bookings with these filters.",
    serviceCol2:              "SERVICE",
    clientCol:                "CLIENT",
    actionCol:                "ACTION",
    confirmAction:            "Confirm",
    markPaidAction:           "Mark as paid",
    completed2:               "Completed",
    bbStatusAll:              "All",
    bbStatusPending:          "Pending",
    bbStatusConfirmed:        "Confirmed",
    bbStatusPaid:             "Paid",
    bbNewBooking:             "+ New Booking",
    bbNewBookingTitle:        "New Booking",
    bbNewBookingDesc:         "Fill in the booking details.",
    bbServiceLabel:           "Service",
    bbServicePlaceholder:     "E.g. Haircut",
    bbDateLabel:              "Date",
    bbTimeLabel:              "Time",
    bbClientLabel:            "Client",
    bbNewClientBtn:           "+ New client",
    bbCancelNewClient:        "✕ Cancel new",
    bbClientNamePlaceholder:  "Name *",
    bbClientPhonePlaceholder: "Phone (optional)",
    bbSaveSelectClient:       "Save and select",
    bbSaving:                 "Saving...",
    bbSelectClient:           "Select a client",
    bbInitialStatus:          "Initial status",
    bbStatusPendingOpt:       "Pending",
    bbStatusConfirmedOpt:     "Confirmed",
    bbCancelBtn:              "Cancel",
    bbCreateBtn:              "Create booking",
    bbStatusUpdated:          "Status updated successfully",
    bbStatusError:            "Could not update the status",
    bbClientCreated:          "client created and selected",
    bbClientError:            "Could not create the client",
    bbBookingCreated:         "Booking created successfully",
    bbBookingError:           "Could not create the booking",

    // Settings
    settingsTitle:            "Settings",
    settingsSubtitle:         "Manage your account and preferences.",
    settingsLanguage:         "Language",
    settingsAppearance:       "Appearance",
    settingsDarkMode:         "Dark mode",
    settingsPassword:         "Change password",
    settingsCurrentPw:        "Current password",
    settingsNewPw:            "New password",
    settingsNewPwMin:         "Min 6 characters (letter & number)",
    settingsConfirmPw:        "Confirm new password",
    settingsRepeatPw:         "Repeat password",
    settingsSaving:           "Saving...",
    settingsUpdatePw:         "Update password",
    settingsPwUpdated:        "Password updated successfully.",
    settingsPwError:          "Error changing the password.",
    settingsPwMismatch:       "Passwords do not match.",
    settingsPwMinLen:         "At least 6 characters, containing a letter and a number.",
    pwFormatHint:             "Minimum 6 characters, containing at least one letter and one number.",
    settings2FA:              "Two-factor authentication",
    settings2FADesc:          "Add an extra layer of security. You will receive a code every time you log in.",
    settings2FAActive:        "Enabled",
    settings2FAInactive:      "Disabled",
    settings2FAStatus:        "Status:",
    settings2FAEnable:        "Enable 2FA",
    settings2FADisable:       "Disable",
    settingsSession:          "Session",
    settingsSessionDesc:      "Log out from this device.",
    settingsLogout:           "Log out",
    modal2FATitle:            "two-factor authentication",
    modal2FAEnableTitle:      "Enable",
    modal2FADisableTitle:     "Disable",
    modal2FAEnableMsg:        "When you enable 2FA, you will receive a code by email every time you log in. Continue?",
    modal2FADisableMsg:       "Are you sure you want to disable two-factor authentication? Your account will be less secure.",
    modal2FAConfirmEnable:    "Yes, enable",
    modal2FAConfirmDisable:   "Yes, disable",

    // Admin Sidebar labels
    myBusiness:               "My business",
    sidebarManagement:        "Management",
    sidebarSystem:            "System",
    sidebarConfig:            "Settings",
    sidebarBusinessRole:      "Verified business",
    sidebarAdminRole:         "Administrator",
    sidebarServices:          "My Services",

    // ConfigTabs
    configAdminGlobal:        "Global Settings (Admin)",
    configSystemTimezone:     "System Timezone",
    configMainCurrency:       "Main Currency",
    configActiveUsers:        "Active Users Management",
    configNewUserVerification:"New registrations require verification",
    configBusinessSettingsTitle:"Business Settings",
    configHoursAndBookings:   "Hours and Appointments",
    configDefaultDuration:    "Default appointment duration (minutes)",
    configMarginBetween:      "Margin between appointments (minutes)",
    configBookingPolicies:    "Booking Policies",
    configMinAdvance:         "Minimum advance to book (hours)",
    configMaxBookings:        "Booking limit per customer (per day)",
    configCustomerPrefs:      "Customer Preferences",
    configNotificationsTitle: "Notifications",
    configEmailReminders:     "Email reminders (24h before)",
    configSMSReminders:       "SMS reminders",
    configPromotions:         "Promotions and news",
    configPrivacyTitle:       "Privacy",
    configRequestDeletion:    "Request account deletion",
    configTabAdmin:           "Administration",
    configTabBusiness:        "My Business",
    configTabCustomer:        "My Account",
    saveChanges:              "Save changes",
    configSavedText:          "Saved!",

    // Admin User Management
    adminManageUsers:         "User Management",
    adminEmail:               "Email",
    adminNewPassword:         "New password (leave blank to keep current)",
    adminEditUser:            "Edit",
    adminDeleteUser:          "Delete",
    adminSaveUser:            "Save",
    adminCancel:              "Cancel",
    adminConfirmDelete:       "Are you sure you want to delete this user? This action cannot be undone.",
    adminNoUsers:             "No other users found.",
    adminLoadingUsers:        "Loading users...",

    // Login / Registration
    loginTitle:               "Log In",
    loginSubtitle:            "Access your dashboard panel",
    emailLabel:               "Email address",
    passwordLabel:            "Password",
    loginBtn:                 "Log in →",
    loggingIn:                "Logging in...",
    createCustomerBtn:        "Create customer account",
    registerBusinessPremium:  "Register my business (Premium)",
    customerRegisterTitle:    "Create account",
    customerRegisterSub:      "Register as a private customer",
    fullNameLabel:            "Full name",
    mobilePhoneLabel:         "Mobile phone",
    confirmPasswordLabel:     "Confirm password",
    registerCustomerBtn:      "Register and log in →",
    registeringText:          "Registering...",
    alreadyHaveAccount:       "Already have an account? Log in",
    businessRegisterTitle:    "Register business",
    bizNameLabel:             "Business name *",
    bizAddressLabel:          "Business address *",
    bizCategoryLabel:         "Category",
    bizPhoneLabel:            "Mobile phone",
    ownerEmailLabel:          "Owner email *",
    ownerPasswordLabel:       "Password *",
    confirmOwnerPasswordLabel: "Confirm *",
    continueToPayment:        "Continue to payment →",
    monthlySubPro:            "Pro Monthly Subscription",
    subPriceMonth:            "14.99 € / month",
    subFeatures:              "✓ Complete booking administration dashboard\n✓ Personal link for your customers\n✓ Unlimited hours and services configuration\n✓ 24/7 support and monthly billing",
    cardHolderLabel:          "Cardholder name",
    cardNumberLabel:          "Card number",
    cardExpiryLabel:          "Expiration",
    payAndCreateAccount:      "Pay 14.99 € and create account →",
    modifyingDataBtn:         "← Modify data",
    secureAccessSSL:          "Secure access and SSL encryption",
    cardNameRequired:         "Please fill in all credit card details.",
    processingSecurePayment:  "Processing secure payment...",
    fillAllRequired:          "Please fill in all required fields.",
    loginHeroTitle:           "Manage bookings\nsmartly",
    loginHeroDesc:            "Modern platform to manage appointments, bookings and clients from an elegant and fast dashboard.",
    loginStatBookings:        "Bookings",
    loginStatBusinesses:      "Businesses",
    loginFormSubDefault:      "Access your management panel",
    loginFormSubBizPayment:   "Enter your bank details to activate the subscription",
    loginFormSubBizData:      "Enter your new business details",
    fullNamePlaceholder:      "John Doe",
    bizNamePlaceholder:       "My Business Ltd",
    bizAddressPlaceholder:    "Main Street 12, London",
    bizCategoryPlaceholder:   "Hair Salon",
    ownerEmailPlaceholder:    "owner@company.com",
    ownerPasswordPlaceholder: "Min. 6 chars",
    repeatPasswordPlaceholder: "Repeat your password",
    cardHolderPlaceholder:    "Full Name",
    subPriceMonthText:        "$14.99 / month",
    payAndCreateAccountText:  "Pay $14.99 and create account →",
    loginErrorIncorrect:      "Incorrect email or password.",
    invalidEmail:             "Please enter a valid email address.",
    phoneMinLength:           "The mobile phone must have at least 9 digits.",
    passwordsMismatch:        "Passwords do not match.",
    passwordMinLength:        "The password must be at least 6 characters long.",
    passwordFormat:           "The password must contain at least one letter and one number.",
    registrationError:        "There was an error creating the account. Please try again.",
    showPasswordLabel:        "Show",
    hidePasswordLabel:        "Hide",
    accountSecurity:          "Account Security",
    introduceCurrentPw:       "Enter your current password",
    profileSecTitle:          "Your account is secure",
    profileSecDesc:           "Your current password is protected by hash encryption in the database. It is recommended to update it periodically.",
    userPanelTitle:           "User Panel",
    userPanelSubtitle:        "Manage your appointments and bookings in your favorite venues",
    conversionRate:           "Conversion Rate",
    paidVsTotal:              "Paid vs Total",
    actionRequired:           "Action Required",
    requireAttention:         "Require Attention",
    totalRevenue:             "Total Revenue",
    revenueSubtitle:          "Accumulated billing",
    pendingCollection:        "Pending Collection",
    pendingPayments:          "Pending payments",
  },

  fr: {
    headerSubtitle:      "Plateforme de gestion des réservations et des paiements",
    darkMode:            "Mode sombre",
    changeLanguage:      "Changer de langue",
    logout:              "Se déconnecter",
    dashboard:           "Tableau de bord",
    bookings:            "Réservations",
    customers:           "Clients",
    payments:            "Paiements",
    business:            "Entreprise",
    adminWorkspace:      "Espace admin",
    dashboardTitle:      "Vue d'ensemble",
    dashboardSubtitle:   "Suivi quotidien des réservations, activités et paiements.",
    totalBookings:       "Total réservations",
    totalBookingsSub:    "Enregistrements en base de données",
    pending:             "En attente",
    pendingSub:          "À confirmer",
    confirmed:           "Confirmées",
    confirmedSub:        "Planifiées",
    paid:                "Payées",
    paidSub:             "Terminées",
    upcomingBookings:    "Prochaines réservations",
    viewAll:             "Voir tout",
    noBookingsYet:       "Aucune réservation enregistrée pour l'instant.",
    date:                "Date",
    time:                "Heure",
    service:             "Service",
    status:              "Statut",
    registeredInSystem:  "Enregistrées dans le système",
    pendingToConfirm:    "En attente de confirmation",
    requireFollowUp:     "Nécessitent un suivi",
    closedBookings:      "Réservations clôturées",
    statusPending:       "En attente",
    statusConfirmed:     "Confirmée",
    statusPaid:          "Payée",
    statusCancelled:     "Annulée",
    bookingsTitle:       "Panneau de rendez-vous",
    bookingsSubtitle:    "Visualisation et gestion des rendez-vous planifiés et prochaines réservations.",
    newBooking:          "+ Nouveau rendez-vous",
    total:               "Total",
    historical:          "Historique",
    inAgenda:            "Planifié",
    completed:           "Terminé",
    upcomingAppointments:"Prochains rendez-vous",
    clientId:            "ID Client",
    serviceCol:          "SERVICE",
    dateTime:            "DATE ET HEURE",
    statusCol:           "STATUT",
    actionsCol:          "ACTIONS",
    edit:                "Modifier",
    delete:              "Supprimer",
    confirmDelete:       "Supprimer cette réservation ?",
    updateAppointment:   "Mettre à jour",
    newAppointment:      "Nouveau rendez-vous",
    fillFields:          "Remplissez les champs pour organiser l'agenda.",
    serviceLabel:        "Service",
    dateLabel:           "Date",
    timeLabel:           "Heure",
    businessLabel:       "Entreprise",
    selectBusiness:      "Sélectionnez une entreprise",
    clientLabel:         "Client",
    selectClient:        "Sélectionnez un client",
    statusLabel:         "Statut",
    cancel:              "Annuler",
    finish:              "Confirmer",
    savedOk:             "Modifications enregistrées avec succès",
    createdOk:           "Rendez-vous planifié avec succès",
    errorMsg:            "Nous n'avons pas pu traiter la demande",
    filterAll:           "Tous",
    customersTitle:      "Répertoire clients",
    customersSubtitle:   "Gestion visuelle des clients et prochaines réservations.",
    newCustomer:         "Nouveau client",
    searchCustomer:      "Rechercher un client...",
    clearSearch:         "Effacer",
    nextBooking:         "Prochaine réservation :",
    noNextBooking:       "Aucune réservation à venir",
    newCustomerModal:    "Nouveau client",
    namePlaceholder:     "Nom",
    phonePlaceholder:    "Téléphone",
    emailPlaceholder:    "Email",
    businessPlaceholder: "Entreprise",
    save:                "Enregistrer",
    customerCreated:     "Client créé avec succès",
    errName:             "Le nom est obligatoire",
    errPhone:            "Le téléphone est obligatoire",
    errPhoneFormat:      "Le téléphone doit avoir 9 chiffres",
    errEmail:            "L'email est obligatoire",
    errEmailFormat:      "L'email n'est pas valide",
    errBusiness:         "L'entreprise est obligatoire",
    paymentsTitle:       "Paiements",
    paymentsSubtitle:    "Suivi des paiements effectués et en attente.",
    registerPayment:     "Enregistrer un paiement",
    collected:           "Encaissé",
    operations:          "opérations",
    toReview:            "à vérifier",
    paymentList:         "Liste des paiements",
    noPaymentsCategory:  "Aucun paiement dans cette catégorie",
    amount:              "Montant",
    method:              "Méthode",
    reservation:         "Réservation",
    markPaid:            "Marquer payé",
    markPending:         "Marquer en attente",
    registerPaymentModal:"Enregistrer un paiement",
    amountPlaceholder:   "Montant (€)",
    paymentMethod:       "Méthode de paiement",
    card:                "Carte",
    cash:                "Espèces",
    transfer:            "Virement",
    toPay:               "À encaisser",
    selectReservation:   "Sélectionnez une réservation",
    paymentRegistered:   "Paiement enregistré avec succès",
    markedPaid:          "Réservation marquée comme payée",
    markedPending:       "Réservation marquée en attente",
    pendingFilter:       "En attente",
    paidFilter:          "Payés",
    seeAll:              "Voir tous",
    businessTitle:       "Entreprises",
    businessSubtitle:    "Gestion des entreprises enregistrées sur la plateforme.",
    newBusiness:         "Nouvelle entreprise",
    active:              "Actif",
    inactive:            "Inactif",
    newBusinessModal:    "Nouvelle entreprise",
    nameBusiness:        "Nom de l'entreprise",
    category:            "Catégorie",
    address:             "Adresse",
    businessCreated:     "Entreprise créée avec succès",
    name:                "Nom",
    email:               "Email",
    phone:               "Téléphone",
    statusBusiness:      "Statut",
    password:            "Mot de passe",

    // Cliente sidebar / área cliente
    mySpace:                  "Mon espace",
    myBusinesses:             "Entreprises",
    myBookings:               "Mes Réservations",
    account:                  "Compte",
    settings:                 "Paramètres",
    clientRole:               "Client",
    bookingPortal:            "Portail de réservation",

    // Mis Reservas (página cliente)
    misReservasTitle:         "Mes Réservations",
    misReservasSubtitle:      "Historique de tous vos rendez-vous et leur statut actuel.",
    newReservation:           "+ Nouvelle réservation",
    reservasCount:            "réservations",
    appointments:             "Rendez-vous",
    loadingText:              "Chargement...",
    noReservas:               "Vous n'avez pas encore de réservations.",
    exploreBusinesses:        "Explorer les entreprises",

    // Nueva Reserva (página cliente)
    nuevaReservaTitle:        "Nouvelle réservation",
    nuevaReservaSubtitle:     "Choisissez une entreprise, le service et la date.",
    goBack:                   "← Retour",
    businessFieldLabel:       "Entreprise *",
    selectBusinessOption:     "Sélectionnez une entreprise",
    serviceFieldLabel:        "Service *",
    servicePlaceholder:       "Ex : Coiffure, Massage, Consultation...",
    dateFieldLabel:           "Date *",
    timeFieldLabel:           "Heure *",
    fillAllFields:            "Veuillez remplir tous les champs.",
    sendingText:              "Envoi...",
    confirmReservation:       "Confirmer la réservation",
    reservaCreada:            "Réservation créée !",
    reservaCreadaMsg:         "Votre rendez-vous est en attente de confirmation par l'entreprise.",
    verMisReservas:           "Voir mes réservations",
    volverEmpresas:           "Retour aux entreprises",
    errorCrearReserva:        "Erreur lors de la création de la réservation. Réessayez.",
    preselectedBusiness:      "sélectionné",

    // Export
    exportReport:             "Exporter le rapport",
    noBookingsExport:         "Aucune réservation à exporter.",

    // Bookings KPIs
    kpiCancelled:             "Annulées",
    kpiCancelledSub:          "Annulées",
    upcomingAppointmentsPanel:"Prochains rendez-vous",

    // Filter pills
    filterPaid:               "Payées",
    filterCancelled:          "Annulées",

    // Delete modal
    deleteModalTitle:         "Supprimer la réservation",
    deleteModalText:          "Voulez-vous vraiment supprimer la réservation",
    deleteModalUndo:          "Cette action est irréversible.",
    deletedOk:                "Réservation supprimée avec succès",

    // Quick create shared
    quickSaving:              "Enregistrement...",
    quickAddNew:              "+ Nouveau",

    // Quick create customer
    quickNewCustomer:         "Nouveau client",
    quickNewCustomerDesc:     "Remplissez les données du nouveau client. Il sera enregistré automatiquement.",
    quickNameLabel:           "Nom *",
    quickNamePlaceholder:     "Nom complet",
    quickEmailLabel:          "Email *",
    quickEmailPlaceholder:    "mail@exemple.com",
    quickPhoneLabel:          "Téléphone *",
    quickPhonePlaceholder:    "612 345 678",
    quickBusinessOptLabel:    "Entreprise (optionnel)",
    quickBusinessPlaceholder: "Nom de l'entreprise",
    quickCreateCustomer:      "Créer le client",
    quickCustomerCreated:     "Client créé avec succès",
    quickCustomerError:       "Erreur lors de la création du client. Réessayez.",
    quickCustomerValidation:  "Nom, email et téléphone sont obligatoires.",

    // Quick create business
    quickNewBusiness:         "Nouvelle entreprise",
    quickNewBusinessDesc:     "Remplissez les données de la nouvelle entreprise. Elle sera enregistrée automatiquement.",
    quickAddressLabel:        "Adresse *",
    quickAddressPlaceholder:  "Rue, numéro, ville",
    quickCategoryLabel:       "Catégorie",
    quickCategoryPlaceholder: "Coiffeur, Spa...",
    quickOwnerEmailLabel:     "Email du propriétaire *",
    quickOwnerEmailPlaceholder:"proprietaire@exemple.com",
    quickOwnerPassLabel:      "Mot de passe du propriétaire *",
    quickOwnerPassPlaceholder:"6 caractères minimum",
    quickCreateBusiness:      "Créer l'entreprise",
    quickBusinessCreated:     "Entreprise créée avec succès",
    quickBusinessError:       "Erreur lors de la création de l'entreprise. Réessayez.",
    quickBusinessValidation:  "Nom, adresse, email et mot de passe du propriétaire sont obligatoires.",

    // Empresas (page client)
    empresasTitle:            "Entreprises disponibles",
    empresasSubtitle:         "Trouvez une entreprise et réservez votre rendez-vous instantanément.",
    activeBusinesses:         "Entreprises actives",
    searchBusinessPlaceholder:"Rechercher par nom, catégorie...",
    loadingBusinesses:        "Chargement des entreprises...",
    noBusinessesFound:        "Aucune entreprise trouvée.",
    bookNow:                  "Réserver",
    businessCol:              "Entreprise",
    categoryCol:              "Catégorie",
    phoneCol:                 "Téléphone",
    addressCol:               "Adresse",
    bookCol:                  "Réserver",

    // Configuración
    configTitle:              "Configuration",
    configSubtitle:           "Paramètres de la plateforme",
    configComingSoon:         "Bientôt disponible — Options de configuration",

    // Business-Bookings
    myBusinessBookings:       "Mes Réservations",
    bbHistorical:             "Historique",
    bbPending:                "En attente",
    bbConfirmed:              "Confirmées",
    bbPaid:                   "Payées",
    bbPendingSub:             "À confirmer",
    bbConfirmedSub:           "Planifiées",
    bbPaidSub:                "Terminées",
    bbTotalSub:               "Total",
    appointmentList:          "Liste des rendez-vous",
    searchServiceClient:      "Rechercher service ou client...",
    loadingBookings:          "Chargement des réservations...",
    noBookingsFilter:         "Aucune réservation avec ces filtres.",
    serviceCol2:              "SERVICE",
    clientCol:                "CLIENT",
    actionCol:                "ACTION",
    confirmAction:            "Confirmer",
    markPaidAction:           "Marquer payé",
    completed2:               "Terminée",
    bbStatusAll:              "Toutes",
    bbStatusPending:          "En attente",
    bbStatusConfirmed:        "Confirmée",
    bbStatusPaid:             "Payée",
    bbNewBooking:             "+ Nouvelle réservation",
    bbNewBookingTitle:        "Nouvelle réservation",
    bbNewBookingDesc:         "Remplissez les données de la réservation.",
    bbServiceLabel:           "Service",
    bbServicePlaceholder:     "Ex : Coiffure",
    bbDateLabel:              "Date",
    bbTimeLabel:              "Heure",
    bbClientLabel:            "Client",
    bbNewClientBtn:           "+ Nouveau client",
    bbCancelNewClient:        "✕ Annuler nouveau",
    bbClientNamePlaceholder:  "Nom *",
    bbClientPhonePlaceholder: "Téléphone (optionnel)",
    bbSaveSelectClient:       "Enregistrer et sélectionner",
    bbSaving:                 "Enregistrement...",
    bbSelectClient:           "Sélectionnez un client",
    bbInitialStatus:          "Statut initial",
    bbStatusPendingOpt:       "En attente",
    bbStatusConfirmedOpt:     "Confirmée",
    bbCancelBtn:              "Annuler",
    bbCreateBtn:              "Créer la réservation",
    bbStatusUpdated:          "Statut mis à jour avec succès",
    bbStatusError:            "Impossible de mettre à jour le statut",
    bbClientCreated:          "client créé et sélectionné",
    bbClientError:            "Impossible de créer le client",
    bbBookingCreated:         "Réservation créée avec succès",
    bbBookingError:           "Impossible de créer la réservation",

    // Settings
    settingsTitle:            "Paramètres",
    settingsSubtitle:         "Gérez votre compte et vos préférences.",
    settingsLanguage:         "Langue",
    settingsAppearance:       "Apparence",
    settingsDarkMode:         "Mode sombre",
    settingsPassword:         "Changer le mot de passe",
    settingsCurrentPw:        "Mot de passe actuel",
    settingsNewPw:            "Nouveau mot de passe",
    settingsNewPwMin:         "6 caract. min (lettre et chiffre)",
    settingsConfirmPw:        "Confirmer le nouveau mot de passe",
    settingsRepeatPw:         "Répétez le mot de passe",
    settingsSaving:           "Enregistrement...",
    settingsUpdatePw:         "Mettre à jour le mot de passe",
    settingsPwUpdated:        "Mot de passe mis à jour avec succès.",
    settingsPwError:          "Erreur lors du changement de mot de passe.",
    settingsPwMismatch:       "Les mots de passe ne correspondent pas.",
    settingsPwMinLen:         "Au moins 6 caractères, avec au moins une lettre et un chiffre.",
    pwFormatHint:             "Au moins 6 caractères, contenant au moins une lettre et un chiffre.",
    settings2FA:              "Authentification à deux facteurs",
    settings2FADesc:          "Ajoutez une couche de sécurité supplémentaire. Vous recevrez un code à chaque connexion.",
    settings2FAActive:        "Activée",
    settings2FAInactive:      "Désactivée",
    settings2FAStatus:        "Statut :",
    settings2FAEnable:        "Activer 2FA",
    settings2FADisable:       "Désactiver",
    settingsSession:          "Session",
    settingsSessionDesc:      "Déconnectez-vous de cet appareil.",
    settingsLogout:           "Se déconnecter",
    modal2FATitle:            "authentification à deux facteurs",
    modal2FAEnableTitle:      "Activer",
    modal2FADisableTitle:     "Désactiver",
    modal2FAEnableMsg:        "En activant le 2FA, vous recevrez un code par email à chaque connexion. Continuer ?",
    modal2FADisableMsg:       "Voulez-vous vraiment désactiver l'authentification à deux facteurs ? Votre compte sera moins sécurisé.",
    modal2FAConfirmEnable:    "Oui, activer",
    modal2FAConfirmDisable:   "Oui, désactiver",

    // Admin Sidebar labels
    myBusiness:               "Mon entreprise",
    sidebarManagement:        "Gestion",
    sidebarSystem:            "Système",
    sidebarConfig:            "Configuration",
    sidebarBusinessRole:      "Entreprise vérifiée",
    sidebarAdminRole:         "Administrateur",
    sidebarServices:          "Mes Services",

    // ConfigTabs
    configAdminGlobal:        "Paramètres Globaux (Admin)",
    configSystemTimezone:     "Fuseau horaire du système",
    configMainCurrency:       "Devise principale",
    configActiveUsers:        "Gestion des utilisateurs actifs",
    configNewUserVerification:"Les nouvelles inscriptions nécessitent une vérification",
    configBusinessSettingsTitle:"Paramètres de l'entreprise",
    configHoursAndBookings:   "Horaires et rendez-vous",
    configDefaultDuration:    "Durée par défaut de chaque rendez-vous (minutes)",
    configMarginBetween:      "Marge entre les rendez-vous (minutes)",
    configBookingPolicies:    "Politiques de réservation",
    configMinAdvance:         "Avance minimale pour réserver (heures)",
    configMaxBookings:        "Limite de réservations par client (par jour)",
    configCustomerPrefs:      "Préférences client",
    configNotificationsTitle: "Notifications",
    configEmailReminders:     "Rappels par email (24h avant)",
    configSMSReminders:       "Rappels par SMS",
    configPromotions:         "Promotions et nouveautés",
    configPrivacyTitle:       "Confidentialité",
    configRequestDeletion:    "Demander la suppression du compte",
    configTabAdmin:           "Administration",
    configTabBusiness:        "Mon Entreprise",
    configTabCustomer:        "Mon Compte",
    saveChanges:              "Enregistrer les modifications",
    configSavedText:          "Enregistré !",

    // Admin User Management
    adminManageUsers:         "Gestion des utilisateurs",
    adminEmail:               "Email",
    adminNewPassword:         "Nouveau mot de passe (laisser vide pour ne pas changer)",
    adminEditUser:            "Modifier",
    adminDeleteUser:          "Supprimer",
    adminSaveUser:            "Enregistrer",
    adminCancel:              "Annuler",
    adminConfirmDelete:       "Voulez-vous vraiment supprimer cet utilisateur ? Cette action est irréversible.",
    adminNoUsers:             "Aucun autre utilisateur trouvé.",
    adminLoadingUsers:        "Chargement des utilisateurs...",

    // Login / Inscription
    loginTitle:               "Se connecter",
    loginSubtitle:            "Accédez à votre tableau de bord",
    emailLabel:               "Adresse e-mail",
    passwordLabel:            "Mot de passe",
    loginBtn:                 "Se connecter →",
    loggingIn:                "Connexion...",
    createCustomerBtn:        "Créer un compte client",
    registerBusinessPremium:  "Enregistrer mon entreprise (Premium)",
    customerRegisterTitle:    "Créer un compte",
    customerRegisterSub:      "Inscrivez-vous en tant que client particulier",
    fullNameLabel:            "Nom complet",
    mobilePhoneLabel:         "Téléphone mobile",
    confirmPasswordLabel:     "Confirmer le mot de passe",
    registerCustomerBtn:      "S'inscrire et se connecter →",
    registeringText:          "Inscription...",
    alreadyHaveAccount:       "Vous avez déjà un compte ? Se connecter",
    businessRegisterTitle:    "Enregistrer l'entreprise",
    bizNameLabel:             "Nom de l'entreprise *",
    bizAddressLabel:          "Adresse de l'entreprise *",
    bizCategoryLabel:         "Catégorie",
    bizPhoneLabel:            "Téléphone mobile",
    ownerEmailLabel:          "E-mail du propriétaire *",
    ownerPasswordLabel:       "Mot de passe *",
    confirmOwnerPasswordLabel: "Confirmer *",
    continueToPayment:        "Continuer vers le paiement →",
    monthlySubPro:            "Abonnement mensuel Pro",
    subPriceMonth:            "14,99 € / mois",
    subFeatures:              "✓ Tableau de bord complet de gestion des réservations\n✓ Lien personnalisé pour vos clients\n✓ Configuration illimitée des horaires et services\n✓ Support 24/7 et facturation mensuelle",
    cardHolderLabel:          "Nom du titulaire",
    cardNumberLabel:          "Numéro de carte",
    cardExpiryLabel:          "Expiration",
    payAndCreateAccount:      "Payer 14,99 € et créer un compte →",
    modifyingDataBtn:         "← Modifier les données",
    secureAccessSSL:          "Accès sécurisé et cryptage SSL",
    cardNameRequired:         "Veuillez remplir toutes les informations de votre carte de crédit.",
    processingSecurePayment:  "Traitement du paiement sécurisé...",
    fillAllRequired:          "Veuillez remplir tous les champs obligatoires.",
    loginHeroTitle:           "Gerez vos reservations\nde maniere intelligente",
    loginHeroDesc:            "Plateforme moderne pour gerer les rendez-vous, les reservations et les clients depuis un tableau de bord elegant et rapide.",
    loginStatBookings:        "Reservations",
    loginStatBusinesses:      "Entreprises",
    loginFormSubDefault:      "Accedez a votre panneau d'administration",
    loginFormSubBizPayment:   "Saisissez vos coordonnees bancaires pour activer l'abonnement",
    loginFormSubBizData:      "Saisissez les informations de votre nouvelle entreprise",
    fullNamePlaceholder:      "Jean Dupont",
    bizNamePlaceholder:       "Mon Entreprise S.A.R.L.",
    bizAddressPlaceholder:    "Rue de Rivoli 12, Paris",
    bizCategoryPlaceholder:   "Salon de coiffure",
    ownerEmailPlaceholder:    "proprietaire@entreprise.com",
    ownerPasswordPlaceholder: "Min. 6 caract.",
    repeatPasswordPlaceholder: "Repetez votre mot de passe",
    cardHolderPlaceholder:    "Nom Complet",
    subPriceMonthText:        "14,99 e / mois",
    payAndCreateAccountText:  "Payer 14,99 e et creer un compte →",
    loginErrorIncorrect:      "E-mail ou mot de passe incorrect.",
    invalidEmail:             "Veuillez entrer une adresse e-mail valide.",
    phoneMinLength:           "Le telephone portable doit comporter au moins 9 chiffres.",
    passwordsMismatch:        "Les mots de passe ne correspondent pas.",
    passwordMinLength:        "Le mot de passe doit comporter au moins 6 caracteres.",
    passwordFormat:           "Le mot de passe doit contenir au moins une lettre et un chiffre.",
    registrationError:        "Une erreur est survenue lors de la creation du compte. Veuillez reessayer.",
    showPasswordLabel:        "Montrer",
    hidePasswordLabel:        "Masquer",
    accountSecurity:          "Securite du compte",
    introduceCurrentPw:       "Entrez votre mot de passe actuel",
    profileSecTitle:          "Votre compte est securise",
    profileSecDesc:           "Votre mot de passe actuel est protege par un cryptage par hachage dans la base de donnees. Il est recommande de le mettre a jour periodiquement.",
    userPanelTitle:           "Tableau de bord de l'utilisateur",
    userPanelSubtitle:        "Gerez vos rendez-vous et reservations dans vos lieux favoris",
    conversionRate:           "Taux de conversion",
    paidVsTotal:              "Payées vs Total",
    actionRequired:           "Action requise",
    requireAttention:         "Nécessitent une attention",
    totalRevenue:             "Revenu Total",
    revenueSubtitle:          "Facturation accumulée",
    pendingCollection:        "En attente de paiement",
    pendingPayments:          "Paiement en attente",
  },
} satisfies Record<LangCode, Record<string, string>>;

export type TranslationKey = keyof typeof translations.es;

interface LanguageContextType {
  lang:    Language;
  setLang: (l: Language) => void;
  t:       (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang:    LANGUAGES[0],
  setLang: () => {},
  t:       (key) => key,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Language>(LANGUAGES[0]);

  useEffect(() => {
    const stored = localStorage.getItem("lang") as LangCode | null;
    if (stored) {
      const found = LANGUAGES.find((l) => l.code === stored);
      if (found) {
        setTimeout(() => setLangState(found), 0);
      }
    }
  }, []);

  const setLang = (l: Language) => {
    setLangState(l);
    localStorage.setItem("lang", l.code);
    document.documentElement.lang = l.code;
  };

  const t = (key: TranslationKey): string =>
    (translations[lang.code] as Record<string, string>)[key] ?? translations.es[key] ?? key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}