"use client";

import { createContext, useContext, useEffect, useState } from "react";

export type LangCode = "es" | "en" | "fr";

export interface Language {
  code: LangCode;
  label: string;
  flag: string;
}

export const LANGUAGES: Language[] = [
  { code: "es", label: "Español",  flag: "🇪🇸" },
  { code: "en", label: "English",  flag: "🇬🇧" },
  { code: "fr", label: "Français", flag: "🇫🇷" },
];

export const translations = {
  es: {
    // Header / menú usuario
    darkMode:            "Modo oscuro",
    changeLanguage:      "Cambiar idioma",
    logout:              "Cerrar sesión",
    headerSubtitle:      "Plataforma de gestión de reservas y cobros",

    // Sidebar
    dashboard:           "Dashboard",
    bookings:            "Reservas",
    customers:           "Clientes",
    payments:            "Pagos",
    business:            "Negocio",
    adminWorkspace:      "Panel de administración",

    // Dashboard
    dashboardTitle:      "Panel de control",
    dashboardSubtitle:   "Control diario de reservas, actividad y pagos.",
    totalBookings:       "Total reservas",
    totalBookingsSub:    "Registros en base de datos",
    pending:             "Pendientes",
    pendingSub:          "Por confirmar",
    confirmed:           "Confirmadas",
    confirmedSub:        "En agenda",
    paid:                "Pagadas",
    paidSub:             "Completadas",
    upcomingBookings:    "Próximas reservas",
    viewAll:             "Ver todas",
    noBookingsYet:       "No hay reservas registradas todavía.",
    date:                "Fecha",
    time:                "Hora",
    service:             "Servicio",
    status:              "Estado",
    registeredInSystem:  "Registradas en el sistema",
    pendingToConfirm:    "Pendientes de confirmar",
    requireFollowUp:     "Requieren seguimiento",
    closedBookings:      "Reservas cerradas",
    statusPending:       "Pendiente",
    statusConfirmed:     "Confirmada",
    statusPaid:          "Pagada",
    statusCancelled:     "Cancelada",

    // Bookings
    bookingsTitle:       "Panel de Citas",
    bookingsSubtitle:    "Visualización y gestión de citas programadas y próximas reservas.",
    newBooking:          "+ Nueva Reserva",
    total:               "Total",
    historical:          "Histórico",
    inAgenda:            "En agenda",
    completed:           "Completado",
    upcomingAppointments:"Próximas Citas",
    clientId:            "ID Cliente",
    serviceCol:          "SERVICIO",
    dateTime:            "FECHA Y HORA",
    statusCol:           "ESTADO",
    actionsCol:          "ACCIONES",
    edit:                "Editar",
    delete:              "Borrar",
    confirmDelete:       "¿Eliminar esta reserva?",
    updateAppointment:   "Actualizar Cita",
    newAppointment:      "Nueva Reserva",
    fillFields:          "Completa los campos para organizar la agenda.",
    serviceLabel:        "Servicio",
    dateLabel:           "Fecha",
    timeLabel:           "Hora",
    businessLabel:       "Negocio",
    selectBusiness:      "Selecciona un negocio",
    clientLabel:         "Cliente",
    selectClient:        "Selecciona un cliente",
    statusLabel:         "Estado",
    cancel:              "Cancelar",
    finish:              "Finalizar",
    savedOk:             "Cambios guardados con éxito",
    createdOk:           "Cita programada correctamente",
    errorMsg:            "No pudimos procesar la solicitud",
    filterAll:           "Ver todas",

    // Customers
    customersTitle:      "Listado de clientes",
    customersSubtitle:   "Gestión visual de clientes y próximas reservas.",
    newCustomer:         "Nuevo cliente",
    searchCustomer:      "Buscar cliente...",
    clearSearch:         "Limpiar",
    nextBooking:         "Próxima reserva:",
    noNextBooking:       "Sin reservas próximas",
    newCustomerModal:    "Nuevo cliente",
    namePlaceholder:     "Nombre",
    phonePlaceholder:    "Teléfono",
    emailPlaceholder:    "Email",
    businessPlaceholder: "Negocio",
    save:                "Guardar",
    customerCreated:     "Cliente creado correctamente",
    errName:             "El nombre es obligatorio",
    errPhone:            "El teléfono es obligatorio",
    errPhoneFormat:      "El teléfono debe tener 9 dígitos",
    errEmail:            "El email es obligatorio",
    errEmailFormat:      "El email no es válido",
    errBusiness:         "El negocio es obligatorio",

    // Payments
    paymentsTitle:       "Payments",
    paymentsSubtitle:    "Seguimiento de cobros realizados y pendientes.",
    registerPayment:     "Registrar cobro",
    collected:           "Cobrado",
    operations:          "operaciones",
    toReview:            "por revisar",
    paymentList:         "Listado de cobros",
    noPaymentsCategory:  "No hay cobros en esta categoría",
    amount:              "Importe",
    method:              "Método",
    reservation:         "Reserva",
    markPaid:            "Marcar pagado",
    markPending:         "Marcar pendiente",
    registerPaymentModal:"Registrar cobro",
    amountPlaceholder:   "Importe (€)",
    paymentMethod:       "Método de pago",
    card:                "Tarjeta",
    cash:                "Efectivo",
    transfer:            "Transferencia",
    toPay:               "Por cobrar",
    selectReservation:   "Selecciona una reserva",
    paymentRegistered:   "Cobro registrado correctamente",
    markedPaid:          "Reserva marcada como pagada",
    markedPending:       "Reserva marcada como pendiente",
    pendingFilter:       "Pendientes",
    paidFilter:          "Pagados",
    seeAll:              "Ver todos",

    // Business
    businessTitle:       "Negocios",
    businessSubtitle:    "Gestión de negocios registrados en la plataforma.",
    newBusiness:         "Nuevo negocio",
    active:              "Activo",
    inactive:            "Inactivo",
    newBusinessModal:    "Nuevo negocio",
    nameBusiness:        "Nombre del negocio",
    category:            "Categoría",
    address:             "Dirección",
    businessCreated:     "Negocio creado correctamente",
    name:                "Nombre",
    email:               "Email",
    phone:               "Teléfono",
    statusBusiness:      "Estado",

    // Export
    exportReport:             "Exportar informe",
    noBookingsExport:         "No hay reservas para exportar.",

    // Bookings KPIs
    kpiCancelled:             "Canceladas",
    kpiCancelledSub:          "Anuladas",
    upcomingAppointmentsPanel:"Próximas Citas",

    // Filter pills
    filterPaid:               "Pagadas",
    filterCancelled:          "Canceladas",

    // Delete modal
    deleteModalTitle:         "Eliminar reserva",
    deleteModalText:          "¿Seguro que quieres eliminar la reserva",
    deleteModalUndo:          "Esta acción no se puede deshacer.",
    deletedOk:                "Reserva eliminada correctamente",

    // Quick create shared
    quickSaving:              "Guardando...",
    quickAddNew:              "+ Nuevo",

    // Quick create customer
    quickNewCustomer:         "Nuevo cliente",
    quickNewCustomerDesc:     "Rellena los datos del nuevo cliente. Se guardará automáticamente.",
    quickNameLabel:           "Nombre *",
    quickNamePlaceholder:     "Nombre completo",
    quickEmailLabel:          "Email *",
    quickEmailPlaceholder:    "correo@ejemplo.com",
    quickPhoneLabel:          "Teléfono *",
    quickPhonePlaceholder:    "612 345 678",
    quickBusinessOptLabel:    "Negocio (opcional)",
    quickBusinessPlaceholder: "Nombre del negocio",
    quickCreateCustomer:      "Crear cliente",
    quickCustomerCreated:     "Cliente creado correctamente",
    quickCustomerError:       "Error al crear el cliente. Inténtalo de nuevo.",
    quickCustomerValidation:  "Nombre, email y teléfono son obligatorios.",

    // Quick create business
    quickNewBusiness:         "Nuevo negocio",
    quickNewBusinessDesc:     "Rellena los datos del nuevo negocio. Se guardará automáticamente.",
    quickAddressLabel:        "Dirección *",
    quickAddressPlaceholder:  "Calle, número, ciudad",
    quickCategoryLabel:       "Categoría",
    quickCategoryPlaceholder: "Peluquería, Spa...",
    quickOwnerEmailLabel:     "Email del propietario *",
    quickOwnerEmailPlaceholder:"propietario@ejemplo.com",
    quickOwnerPassLabel:      "Contraseña del propietario *",
    quickOwnerPassPlaceholder:"Mínimo 6 caracteres",
    quickCreateBusiness:      "Crear negocio",
    quickBusinessCreated:     "Negocio creado correctamente",
    quickBusinessError:       "Error al crear el negocio. Inténtalo de nuevo.",
    quickBusinessValidation:  "Nombre, dirección, email y contraseña del propietario son obligatorios.",
  },

  en: {
    headerSubtitle:      "Booking and payment management platform",
    darkMode:            "Dark mode",
    changeLanguage:      "Change language",
    logout:              "Log out",
    dashboard:           "Dashboard",
    bookings:            "Bookings",
    customers:           "Customers",
    payments:            "Payments",
    business:            "Business",
    adminWorkspace:      "Admin workspace",
    dashboardTitle:      "Dashboard overview",
    dashboardSubtitle:   "Daily overview of bookings, activity and payments.",
    totalBookings:       "Total bookings",
    totalBookingsSub:    "Records in database",
    pending:             "Pending",
    pendingSub:          "To confirm",
    confirmed:           "Confirmed",
    confirmedSub:        "In schedule",
    paid:                "Paid",
    paidSub:             "Completed",
    upcomingBookings:    "Upcoming bookings",
    viewAll:             "View all",
    noBookingsYet:       "No bookings registered yet.",
    date:                "Date",
    time:                "Time",
    service:             "Service",
    status:              "Status",
    registeredInSystem:  "Registered in the system",
    pendingToConfirm:    "Pending to confirm",
    requireFollowUp:     "Require follow-up",
    closedBookings:      "Closed bookings",
    statusPending:       "Pending",
    statusConfirmed:     "Confirmed",
    statusPaid:          "Paid",
    statusCancelled:     "Cancelled",
    bookingsTitle:       "Appointments Panel",
    newBooking:          "+ New Booking",
    total:               "Total",
    historical:          "Historical",
    inAgenda:            "In schedule",
    completed:           "Completed",
    upcomingAppointments:"Upcoming Appointments",
    clientId:            "Client ID",
    serviceCol:          "SERVICE",
    dateTime:            "DATE & TIME",
    statusCol:           "STATUS",
    actionsCol:          "ACTIONS",
    edit:                "Edit",
    delete:              "Delete",
    confirmDelete:       "Delete this booking?",
    updateAppointment:   "Update Appointment",
    newAppointment:      "New Booking",
    fillFields:          "Fill in the fields to organise the schedule.",
    serviceLabel:        "Service",
    dateLabel:           "Date",
    timeLabel:           "Time",
    businessLabel:       "Business",
    selectBusiness:      "Select a business",
    clientLabel:         "Client",
    selectClient:        "Select a client",
    statusLabel:         "Status",
    cancel:              "Cancel",
    finish:              "Confirm",
    savedOk:             "Changes saved successfully",
    createdOk:           "Appointment scheduled successfully",
    errorMsg:            "We could not process the request",
    filterAll:           "All",
    customersTitle:      "Customer directory",
    customersSubtitle:   "Visual management of customers and upcoming bookings.",
    newCustomer:         "New customer",
    searchCustomer:      "Search customer...",
    clearSearch:         "Clear",
    nextBooking:         "Next booking:",
    noNextBooking:       "No upcoming bookings",
    newCustomerModal:    "New customer",
    namePlaceholder:     "Name",
    phonePlaceholder:    "Phone",
    emailPlaceholder:    "Email",
    businessPlaceholder: "Business",
    save:                "Save",
    customerCreated:     "Customer created successfully",
    errName:             "Name is required",
    errPhone:            "Phone is required",
    errPhoneFormat:      "Phone must have 9 digits",
    errEmail:            "Email is required",
    errEmailFormat:      "Email is not valid",
    errBusiness:         "Business is required",
    paymentsTitle:       "Payments",
    paymentsSubtitle:    "Track completed and pending payments.",
    registerPayment:     "Register payment",
    collected:           "Collected",
    operations:          "operations",
    toReview:            "to review",
    paymentList:         "Payment list",
    noPaymentsCategory:  "No payments in this category",
    amount:              "Amount",
    method:              "Method",
    reservation:         "Booking",
    markPaid:            "Mark as paid",
    markPending:         "Mark as pending",
    registerPaymentModal:"Register payment",
    amountPlaceholder:   "Amount (€)",
    paymentMethod:       "Payment method",
    card:                "Card",
    cash:                "Cash",
    transfer:            "Transfer",
    toPay:               "To collect",
    selectReservation:   "Select a booking",
    paymentRegistered:   "Payment registered successfully",
    markedPaid:          "Booking marked as paid",
    markedPending:       "Booking marked as pending",
    pendingFilter:       "Pending",
    paidFilter:          "Paid",
    seeAll:              "See all",
    businessTitle:       "Businesses",
    businessSubtitle:    "Management of businesses registered on the platform.",
    newBusiness:         "New business",
    active:              "Active",
    inactive:            "Inactive",
    newBusinessModal:    "New business",
    nameBusiness:        "Business name",
    category:            "Category",
    address:             "Address",
    businessCreated:     "Business created successfully",
    name:                "Name",
    email:               "Email",
    phone:               "Phone",
    statusBusiness:      "Status",

    // Export
    exportReport:             "Export report",
    noBookingsExport:         "No bookings to export.",

    // Bookings KPIs
    kpiCancelled:             "Cancelled",
    kpiCancelledSub:          "Cancelled",
    upcomingAppointmentsPanel:"Upcoming Appointments",

    // Filter pills
    filterPaid:               "Paid",
    filterCancelled:          "Cancelled",

    // Delete modal
    deleteModalTitle:         "Delete booking",
    deleteModalText:          "Are you sure you want to delete booking",
    deleteModalUndo:          "This action cannot be undone.",
    deletedOk:                "Booking deleted successfully",

    // Quick create shared
    quickSaving:              "Saving...",
    quickAddNew:              "+ New",

    // Quick create customer
    quickNewCustomer:         "New customer",
    quickNewCustomerDesc:     "Fill in the new customer's details. It will be saved automatically.",
    quickNameLabel:           "Name *",
    quickNamePlaceholder:     "Full name",
    quickEmailLabel:          "Email *",
    quickEmailPlaceholder:    "mail@example.com",
    quickPhoneLabel:          "Phone *",
    quickPhonePlaceholder:    "612 345 678",
    quickBusinessOptLabel:    "Business (optional)",
    quickBusinessPlaceholder: "Business name",
    quickCreateCustomer:      "Create customer",
    quickCustomerCreated:     "Customer created successfully",
    quickCustomerError:       "Error creating the customer. Please try again.",
    quickCustomerValidation:  "Name, email and phone are required.",

    // Quick create business
    quickNewBusiness:         "New business",
    quickNewBusinessDesc:     "Fill in the new business details. It will be saved automatically.",
    quickAddressLabel:        "Address *",
    quickAddressPlaceholder:  "Street, number, city",
    quickCategoryLabel:       "Category",
    quickCategoryPlaceholder: "Hair salon, Spa...",
    quickOwnerEmailLabel:     "Owner email *",
    quickOwnerEmailPlaceholder:"owner@example.com",
    quickOwnerPassLabel:      "Owner password *",
    quickOwnerPassPlaceholder:"At least 6 characters",
    quickCreateBusiness:      "Create business",
    quickBusinessCreated:     "Business created successfully",
    quickBusinessError:       "Error creating the business. Please try again.",
    quickBusinessValidation:  "Name, address, email and owner password are required.",
  },

  fr: {
    headerSubtitle:      "Plateforme de gestion des réservations et des paiements",
    darkMode:            "Mode sombre",
    changeLanguage:      "Changer de langue",
    logout:              "Se déconnecter",
    dashboard:           "Tableau de bord",
    bookings:            "Réservations",
    customers:           "Clients",
    payments:            "Paiements",
    business:            "Entreprise",
    adminWorkspace:      "Espace admin",
    dashboardTitle:      "Vue d'ensemble",
    dashboardSubtitle:   "Suivi quotidien des réservations, activités et paiements.",
    totalBookings:       "Total réservations",
    totalBookingsSub:    "Enregistrements en base de données",
    pending:             "En attente",
    pendingSub:          "À confirmer",
    confirmed:           "Confirmées",
    confirmedSub:        "Planifiées",
    paid:                "Payées",
    paidSub:             "Terminées",
    upcomingBookings:    "Prochaines réservations",
    viewAll:             "Voir tout",
    noBookingsYet:       "Aucune réservation enregistrée pour l'instant.",
    date:                "Date",
    time:                "Heure",
    service:             "Service",
    status:              "Statut",
    registeredInSystem:  "Enregistrées dans le système",
    pendingToConfirm:    "En attente de confirmation",
    requireFollowUp:     "Nécessitent un suivi",
    closedBookings:      "Réservations clôturées",
    statusPending:       "En attente",
    statusConfirmed:     "Confirmée",
    statusPaid:          "Payée",
    statusCancelled:     "Annulée",
    bookingsTitle:       "Panneau de rendez-vous",
    newBooking:          "+ Nouveau rendez-vous",
    total:               "Total",
    historical:          "Historique",
    inAgenda:            "Planifié",
    completed:           "Terminé",
    upcomingAppointments:"Prochains rendez-vous",
    clientId:            "ID Client",
    serviceCol:          "SERVICE",
    dateTime:            "DATE ET HEURE",
    statusCol:           "STATUT",
    actionsCol:          "ACTIONS",
    edit:                "Modifier",
    delete:              "Supprimer",
    confirmDelete:       "Supprimer cette réservation ?",
    updateAppointment:   "Mettre à jour",
    newAppointment:      "Nouveau rendez-vous",
    fillFields:          "Remplissez les champs pour organiser l'agenda.",
    serviceLabel:        "Service",
    dateLabel:           "Date",
    timeLabel:           "Heure",
    businessLabel:       "Entreprise",
    selectBusiness:      "Sélectionnez une entreprise",
    clientLabel:         "Client",
    selectClient:        "Sélectionnez un client",
    statusLabel:         "Statut",
    cancel:              "Annuler",
    finish:              "Confirmer",
    savedOk:             "Modifications enregistrées avec succès",
    createdOk:           "Rendez-vous planifié avec succès",
    errorMsg:            "Nous n'avons pas pu traiter la demande",
    filterAll:           "Tous",
    customersTitle:      "Répertoire clients",
    customersSubtitle:   "Gestion visuelle des clients et prochaines réservations.",
    newCustomer:         "Nouveau client",
    searchCustomer:      "Rechercher un client...",
    clearSearch:         "Effacer",
    nextBooking:         "Prochaine réservation :",
    noNextBooking:       "Aucune réservation à venir",
    newCustomerModal:    "Nouveau client",
    namePlaceholder:     "Nom",
    phonePlaceholder:    "Téléphone",
    emailPlaceholder:    "Email",
    businessPlaceholder: "Entreprise",
    save:                "Enregistrer",
    customerCreated:     "Client créé avec succès",
    errName:             "Le nom est obligatoire",
    errPhone:            "Le téléphone est obligatoire",
    errPhoneFormat:      "Le téléphone doit avoir 9 chiffres",
    errEmail:            "L'email est obligatoire",
    errEmailFormat:      "L'email n'est pas valide",
    errBusiness:         "L'entreprise est obligatoire",
    paymentsTitle:       "Paiements",
    paymentsSubtitle:    "Suivi des paiements effectués et en attente.",
    registerPayment:     "Enregistrer un paiement",
    collected:           "Encaissé",
    operations:          "opérations",
    toReview:            "à vérifier",
    paymentList:         "Liste des paiements",
    noPaymentsCategory:  "Aucun paiement dans cette catégorie",
    amount:              "Montant",
    method:              "Méthode",
    reservation:         "Réservation",
    markPaid:            "Marquer payé",
    markPending:         "Marquer en attente",
    registerPaymentModal:"Enregistrer un paiement",
    amountPlaceholder:   "Montant (€)",
    paymentMethod:       "Méthode de paiement",
    card:                "Carte",
    cash:                "Espèces",
    transfer:            "Virement",
    toPay:               "À encaisser",
    selectReservation:   "Sélectionnez une réservation",
    paymentRegistered:   "Paiement enregistré avec succès",
    markedPaid:          "Réservation marquée comme payée",
    markedPending:       "Réservation marquée en attente",
    pendingFilter:       "En attente",
    paidFilter:          "Payés",
    seeAll:              "Voir tous",
    businessTitle:       "Entreprises",
    businessSubtitle:    "Gestion des entreprises enregistrées sur la plateforme.",
    newBusiness:         "Nouvelle entreprise",
    active:              "Actif",
    inactive:            "Inactif",
    newBusinessModal:    "Nouvelle entreprise",
    nameBusiness:        "Nom de l'entreprise",
    category:            "Catégorie",
    address:             "Adresse",
    businessCreated:     "Entreprise créée avec succès",
    name:                "Nom",
    email:               "Email",
    phone:               "Téléphone",
    statusBusiness:      "Statut",

    // Export
    exportReport:             "Exporter le rapport",
    noBookingsExport:         "Aucune réservation à exporter.",

    // Bookings KPIs
    kpiCancelled:             "Annulées",
    kpiCancelledSub:          "Annulées",
    upcomingAppointmentsPanel:"Prochains rendez-vous",

    // Filter pills
    filterPaid:               "Payées",
    filterCancelled:          "Annulées",

    // Delete modal
    deleteModalTitle:         "Supprimer la réservation",
    deleteModalText:          "Voulez-vous vraiment supprimer la réservation",
    deleteModalUndo:          "Cette action est irréversible.",
    deletedOk:                "Réservation supprimée avec succès",

    // Quick create shared
    quickSaving:              "Enregistrement...",
    quickAddNew:              "+ Nouveau",

    // Quick create customer
    quickNewCustomer:         "Nouveau client",
    quickNewCustomerDesc:     "Remplissez les données du nouveau client. Il sera enregistré automatiquement.",
    quickNameLabel:           "Nom *",
    quickNamePlaceholder:     "Nom complet",
    quickEmailLabel:          "Email *",
    quickEmailPlaceholder:    "mail@exemple.com",
    quickPhoneLabel:          "Téléphone *",
    quickPhonePlaceholder:    "612 345 678",
    quickBusinessOptLabel:    "Entreprise (optionnel)",
    quickBusinessPlaceholder: "Nom de l'entreprise",
    quickCreateCustomer:      "Créer le client",
    quickCustomerCreated:     "Client créé avec succès",
    quickCustomerError:       "Erreur lors de la création du client. Réessayez.",
    quickCustomerValidation:  "Nom, email et téléphone sont obligatoires.",

    // Quick create business
    quickNewBusiness:         "Nouvelle entreprise",
    quickNewBusinessDesc:     "Remplissez les données de la nouvelle entreprise. Elle sera enregistrée automatiquement.",
    quickAddressLabel:        "Adresse *",
    quickAddressPlaceholder:  "Rue, numéro, ville",
    quickCategoryLabel:       "Catégorie",
    quickCategoryPlaceholder: "Coiffeur, Spa...",
    quickOwnerEmailLabel:     "Email du propriétaire *",
    quickOwnerEmailPlaceholder:"proprietaire@exemple.com",
    quickOwnerPassLabel:      "Mot de passe du propriétaire *",
    quickOwnerPassPlaceholder:"6 caractères minimum",
    quickCreateBusiness:      "Créer l'entreprise",
    quickBusinessCreated:     "Entreprise créée avec succès",
    quickBusinessError:       "Erreur lors de la création de l'entreprise. Réessayez.",
    quickBusinessValidation:  "Nom, adresse, email et mot de passe du propriétaire sont obligatoires.",
  },
} satisfies Record<LangCode, Record<string, string>>;

export type TranslationKey = keyof typeof translations.es;

interface LanguageContextType {
  lang:    Language;
  setLang: (l: Language) => void;
  t:       (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang:    LANGUAGES[0],
  setLang: () => {},
  t:       (key) => key,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Language>(LANGUAGES[0]);

  useEffect(() => {
    const stored = localStorage.getItem("lang") as LangCode | null;
    if (stored) {
      const found = LANGUAGES.find((l) => l.code === stored);
      if (found) setLangState(found);
    }
  }, []);

  const setLang = (l: Language) => {
    setLangState(l);
    localStorage.setItem("lang", l.code);
    document.documentElement.lang = l.code;
  };

  const t = (key: TranslationKey): string =>
    translations[lang.code][key] ?? translations.es[key] ?? key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}